#!/bin/bash

## PermitRootLogin for ssh
sed -i '/#PermitRootLogin prohibit-password/c\PermitRootLogin yes' output/target/etc/ssh/sshd_config 


## change prompt to MP3_SHELL> with blue color
sed -i "/export PS1=/c\                 export PS1='MP3_SHELL>  '"  output/target/etc/profile


## aliasing ls -lah
echo 'alias las="ls -lah"' >> output/target/etc/profile

# creating the directory for playmusic
if [ ! -d "${TARGET_DIR}/root/superMusic" ]; then
	sudo mkdir ${TARGET_DIR}/root/superMusic
fi


#creating aliases for the command line
echo "alias play=$'echo \"PLAY_FLAG=1\nPAUSE_FLAG=0\nSHUFFLE_FLAG=0\nNEXT_FLAG=0\nPREVIOUS_FLAG=0\" > /root/superMusic/commandLines.conf'" >> output/target/etc/profile 

echo "alias pause=$'echo \"PLAY_FLAG=0\nPAUSE_FLAG=1\nSHUFFLE_FLAG=0\nNEXT_FLAG=0\nPREVIOUS_FLAG=0\" > /root/superMusic/commandLines.conf'" >> output/target/etc/profile 

echo "alias shuffle=$'echo \"PLAY_FLAG=0\nPAUSE_FLAG=0\nSHUFFLE_FLAG=1\nNEXT_FLAG=0\nPREVIOUS_FLAG=0\" > /root/superMusic/commandLines.conf'" >> output/target/etc/profile 

echo "alias next=$'echo \"PLAY_FLAG=0\nPAUSE_FLAG=0\nSHUFFLE_FLAG=0\nNEXT_FLAG=1\nPREVIOUS_FLAG=0\" > /root/superMusic/commandLines.conf'" >> output/target/etc/profile 

echo "alias previous=$'echo \"PLAY_FLAG=0\nPAUSE_FLAG=0\nSHUFFLE_FLAG=0\nNEXT_FLAG=0\nPREVIOUS_FLAG=1\" > /root/superMusic/commandLines.conf'" >> output/target/etc/profile 


#copying the playmusic daemon to ${TARGET_DIR}/etc/init.d/
sudo cp $(dirname $0)/playmusic/S50-playmusic-daemon-service ${TARGET_DIR}/etc/init.d/
#changing the file mod to be executed
sudo chmod 777 ${TARGET_DIR}/etc/init.d/S50-playmusic-daemon-service

#copying playmusic scripts to superMusic directory
sudo cp $(dirname $0)/playmusic/playmusic* ${TARGET_DIR}/root/superMusic/

#copying any .mp3 files on the image disk to superMusic directory
sudo cp $(dirname $0)/playmusic/*.mp3 ${TARGET_DIR}/root/superMusic/

#copying the USB detection script to superMusic directory
sudo cp $(dirname $0)/playmusic/detectUSB ${TARGET_DIR}/root/superMusic/
sudo cp $(dirname $0)/playmusic/startBluetooth ${TARGET_DIR}/root/superMusic/
sudo chmod -R 777 ${TARGET_DIR}/root
# Install music


####################################### Enabling Wifi #######################################
if [ ! -d "${TARGET_DIR}/etc/wpa_supplicant" ]; then
	sudo mkdir ${TARGET_DIR}/etc/wpa_supplicant
fi
sudo chmod 777 ${TARGET_DIR}/etc/wpa_supplicant

if [ ! -f "${TARGET_DIR}/etc/wpa_supplicant/wpa_supplicant.conf" ]; then
	sudo touch ${TARGET_DIR}/etc/wpa_supplicant/wpa_supplicant.conf
fi
sudo chmod 777 ${TARGET_DIR}/etc/wpa_supplicant/wpa_supplicant.conf


#Loading the coldplug configurations
sudo cp package/busybox/S10mdev ${TARGET_DIR}/etc/init.d/S10mdev
sudo chmod 777 ${TARGET_DIR}/etc/init.d/S10mdev

sudo cp package/busybox/mdev.conf ${TARGET_DIR}/etc/mdev.conf
sudo chmod 777 ${TARGET_DIR}/etc/mdev.conf


## make static ip
cat > output/target/etc/network/interfaces << EOL
# interface file auto-generated by buildroot
auto lo
iface lo inet loopback

#iface eth0 inet dhcp
auto eth0
iface eth0 inet static
wait-delay 15
#hostname $(hostname)
address 192.168.0.6
netmask 255.255.255.0

#auto wlan0
#iface wlan0 inet static
#address 192.168.1.201
#netmask 255.255.255.0
#pre-up wpa_supplicant -B -Dwext -iwlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf
#post-down killall -q wpa_supplicant
#wait-delay 15
#iface default inet dhcp
EOL


#Adding details about the available Wifi networks
cat > output/target/etc/wpa_supplicant/wpa_supplicant.conf << EOL
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=EG

network={

	ssid="OrangeDSL-AnnoyingORANGE"
	# this is needed if the ssid is not being broadcasted
   	scan_ssid=1
        psk="88888999990"
        key_mgmt=WPA-PSK
}
EOL



